sprinter: abort if http code changes between transfers
curl/relative pull request #2
Opened 2021-08-29 06:36 UTC by jay

.. because without that consistency the final measurement cannot be
accurately used for comparison.

Closes #xxxx

---

This change could be further improved because currently it doesn't enforce between curl versions. In other words a server could return http code 123 for curl 7.50 and http code 456 for curl 7.60. I don't know how we'd do that except just enforce 200 instead, or pass the expected http code as an argument.

2021-08-29 06:49 UTC, jay commented
> I don't know how we'd do that except just enforce 200 instead, or pass the expected http code as an argument.

I redid it to do that in a separate commit that can be squashed, this way the original proposal can be seen. I think the most recent change better.

2023-01-01 08:27 UTC, Reclick55 requested changes
Changes from be blocked on index on rewards and
Payouts

2023-03-07 22:37 UTC, bagder approved these changes

2023-03-07 22:38 UTC, merged

2023-03-07 22:38 UTC, bagder commented
Thanks, sorry I had forgot about this!